# -*- coding: utf-8 -*-
"""beautiful_soup_winter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vpvl-_Mcs0C2d5fzM__g_qqFqPqujRCh
"""

from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
import matplotlib.pyplot as plt
import re
import numpy as np

url = "https://www.hubertiming.com/results/2023WyEasterLong"
html = urlopen(url)
soup = BeautifulSoup(html, "lxml")

print(type(soup))
title= soup.title
print(title)

text = soup.get_text()
print(soup.text)

# Extract all hyperlinks
all_links = soup.find_all("a")
for link in all_links:
    print(link.get("href"))

rows = soup.find_all('tr')
print(rows[:10])

list_rows = []
for row in rows:
    cells = row.find_all('td')
    str_cells = str(cells)
    clean = re.compile('<.*?>')
    clean2 = (re.sub(clean, '',str_cells))
    list_rows.append(clean2)
print(clean2)
type(clean2)

df = pd.DataFrame(list_rows)
df.head(10)

df1 = df[0].str.split(',', expand=True)
df1.head(10)

df1[0] = df1[0].str.strip('[')
df1.head(10)

col_labels = soup.find_all('th')
# Convert the header cells to string
col_str = str(col_labels)

# Use BeautifulSoup again to strip away any HTML tags
cleantext2 = BeautifulSoup(col_str, "lxml").get_text()

# Append the cleaned header string to a list
all_header = []
all_header.append(cleantext2)

# Print the header row as a list
print(all_header)

df2 = pd.DataFrame(all_header)
df2.head()
df3 = df2[0].str.split(',', expand=True)
df3.head()

frames = [df3, df1]
df4 = pd.concat(frames, ignore_index=True)
df4.head(10)

df5 = df4.rename(columns=df4.iloc[0])
df5 = df5.drop(df5.index[0])
df5.head()
df6 = df5.dropna(axis=0, how='any')

print(df6.info())
print(df6.shape)

df7 = df6.drop(df6.index[0])
df7.head()

df7.rename(columns={'[Place': 'Place'},inplace=True)
df7.rename(columns={' Age Group Place]': 'Age Group Place'},inplace=True)
df7.head()

df7['Age Group Place'] = df7['Age Group Place'].str.strip(']')
df7.head()

time_list = df7[' Time'].tolist()

# Convert 'Time' to minutes
time_mins = []
for i in time_list:
    time_parts = i.split(':')

    # If the time string doesn't have 3 parts (hours, minutes, seconds)
    if len(time_parts) == 2:
        # Handle cases where the format is "mm:ss"
        m, s = time_parts
        h = 0
    elif len(time_parts) == 3:
        # Standard format "hh:mm:ss"
        h, m, s = time_parts
    else:
        # Skip if the format is not valid
        continue

    # Convert time to minutes
    math = (int(h) * 3600 + int(m) * 60 + int(s)) / 60
    time_mins.append(math)

# Check the first few values of time_mins
print(time_mins[:10])

# Create a new column in df7 with the time in minutes
df7['skimo_mins'] = time_mins

# Check the first few rows of the dataframe to see the new column
df7.head()

df7.describe(include=[np.number])

from pylab import rcParams
import matplotlib.pyplot as plt

# Set the figure size for all plots
rcParams['figure.figsize'] = 15, 5

# Create a boxplot for the 'Runner_mins' column
df7.boxplot(column='skimo_mins')

# Add grid lines along the y-axis
plt.grid(True, axis='y')

# Set the y-axis label
plt.ylabel('Time')

# Set x-tick labels
plt.xticks([1], ['Player'])

# Show the plot
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Extract the 'Runner_mins' column from df7
x = df7['skimo_mins']

# Plot histogram with KDE (Kernel Density Estimate)
plt.figure(figsize=(10, 6))
sns.histplot(x, kde=True, color='m', bins=25, edgecolor='black')

# Show the plot
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
f_fuko = df7.loc[df7[' Gender']==' F']['skimo_mins']
m_fuko = df7.loc[df7[' Gender']==' M']['skimo_mins']

sns.distplot(f_fuko, hist=True, kde=True, rug=False, hist_kws={'edgecolor':'black'}, label='Female')
sns.distplot(m_fuko, hist=False, kde=True, rug=False, hist_kws={'edgecolor':'black'}, label='Male')

plt.legend()

# Show the plot
plt.show()

df7.boxplot(column='skimo_mins', by=' Gender')
plt.ylabel('Chip Time')
plt.suptitle("")